# Generated by Django 6.0.6 on 2026-06-22 19:51

from django.db import migrations


def crear_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    administradores, _ = Group.objects.get_or_create(name='Administradores')
    empleados, _ = Group.objects.get_or_create(name='Empleados')

    modelos_admin = ['vino', 'bodega', 'proveedor', 'compra']
    acciones_admin = ['add', 'change', 'delete', 'view']
    perms_admin = Permission.objects.filter(
        content_type__app_label='vinoteca',
        content_type__model__in=modelos_admin,
        codename__in=[f'{a}_{m}' for a in acciones_admin for m in modelos_admin],
    )
    administradores.permissions.set(perms_admin)

    perms_empleados = Permission.objects.filter(
        content_type__app_label='vinoteca',
        content_type__model__in=['vino', 'compra'],
        codename__in=['add_vino', 'view_vino', 'add_compra', 'view_compra'],
    )
    empleados.permissions.set(perms_empleados)


def eliminar_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Administradores', 'Empleados']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(crear_grupos, eliminar_grupos),
    ]
